runtime: python38
env: standard
# The number of workers (-w #) should match the specified instance class.
# Check https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices for more information.
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app
instance_class: F2
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
  min_idle_instances: 1
  min_instances: 1
  max_instances: 5
network: {}
inbound_services:
- warmup
